name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest-html-reporter

      - name: Install containerd.io and Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y containerd.io docker-ce docker-ce-cli

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: |
          npm install

      - name: Start Docker Compose and wait
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Create admin user
        run: |
          docker exec evershop-automation-tests_app_1 npm run user:create -- --email "rosievanyan@gmail.com" --password "Davinchi6" --name "ruzik_vanyan"

      - name: Run tests and generate HTML report
        run: |
          source venv/bin/activate
          pytest

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: pytest_html_report.html

      - name: Shutdown Docker Compose
        run: |
          docker-compose down
